kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
  namespace: nicholson-adlaon-dev
  uid: 7ad6d66d-9dea-4d44-a2f0-06e4b7d1eebe
  resourceVersion: '4238024168'
  creationTimestamp: '2024-04-23T07:23:52Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-04-26T05:47:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:nginx.conf': {}
data:
  nginx.conf: |
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;
    events {
    worker_connections  4096;
    }
    http {
        include  /etc/nginx/mime.types;
        include /etc/nginx/conf.d/*.conf;
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;
        server {
            listen 8080;
            listen [::]:8080;
            
            server_name 172.30.110.148; # POD_IP
            
            location / {
                 proxy_pass http://172.30.108.72:8080/;
                 proxy_set_header Host $host;
            }
        }
    }
